### ISSUE TITLE
La ligne qui permet d'encoder le texte pour W10 retourne une exception

### ISSUE THREAD

**Issue by Calibanda** [lyghtnox/pacepo#1]
La ligne 92 du main, qui ne s'exectue que si le script tourne sous windows retourne l'exception :
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 0: invalid start byte`
Il suffit d’ôter la ligne (et l'instruction conditionnelle dans laquelle elle se trouve) pour que le programme s'execute normalement.

**Comment by lyghtnox** [comment]
Solved in #2
